### ISSUE TITLE
Page Speed Insights

### ISSUE THREAD

**Issue by Pauldominick** [stefanobartoletti/bricks#358]
Hi Stefano,

One thing about this theme is it speed and I have never seen any other theme performing amzing in page speed insights. 

For me it showed 98 for mobile devices and 100 for desktop.

But when I put google adsense and analytics code (tried manullay placing the code in header.php as well as used google site kit plugin), the page speed goes to 40-50 for mobile. Desktop still performing great with 95. 

I know this is completly independed of your theme scope as these are 3rd party codes. Is there any suggestions or help to increase the page speed with google adsense code?

Please refer to the SS

![Screenshot 2022-08-28 10 18 33 AM](https://user-images.githubusercontent.com/111431847/187058288-5b461fc2-0680-44fb-9117-526e1d2e5e62.png)
![Screenshot 2022-08-28 10 17 45 AM-01](https://user-images.githubusercontent.com/111431847/187058301-55cc560a-6a58-45f5-85bb-4f1dcde77461.jpeg)
![Screenshot 2022-08-28 10 18 05 AM-02](https://user-images.githubusercontent.com/111431847/187058306-f8883851-2d57-46d0-9f8d-79679e70b786.jpeg)

Thanks

Paul

**Comment by stefanobartoletti** [comment]
Thank you for your feedback!

As you already point out, these are external scripts, which can't be really addressed by the theme. What you are doing here is calling for a script that is provided as is. that maybe brings in its own resources like CSS or Images, that affect the overall page weight, but that you can't directly control.

The difference in score between desktop and mobile is quite normal, all websites that I test on PageSpeed Insights report this. 
I think that there are stricter requirements on the mobile tests, that consider a slower connection over a cabled desktop one, hence the lower scores.

I'm sure that you have already done your googling about this, but I found an article that seems to suggest some strategies to improve the page loading speed and thus the score: https://wpadvancedads.com/adsense-page-speed-core-web-vitals/. See if it is useful in your case.

Since we are talking about external scripts, you can also consider indirectly addressing this problem by optimizing as much as possible all internal resources, you can try with [Hummingbird](https://wordpress.org/plugins/hummingbird-performance/) and [Smush](https://wordpress.org/plugins/wp-smushit/) respectively for code and image optimization, but there are a lot of other similar plugins.

**Comment by Pauldominick** [comment]
Thank you for your immensely helpful Suggestions. I have also looked into the article that you have shared. It's amazing and informative.
