### ISSUE TITLE
Rename theme?

### ISSUE THREAD

**Issue by z-website** [stefanobartoletti/bricks#42]
Hello Stefano!
How do I rename a theme correctly? And do you use a child theme with Brick?

**Comment by stefanobartoletti** [comment]
Hi, you can modify the `textdomain` variable inside `bricks.config.js`, as described here: https://bricks.stefanobartoletti.it/theme/configuration/#project-variables

You will probably need to accordingly rename also the theme directory.

I don't usually use a child theme with Bricks, it is just a very simple starter for developers (you don't really need to update it once starting a project), also I'm not sure on how you would use preconfigured Gulp tasks from a child.

**Comment by z-website** [comment]
Thanks for the quick response.
I started using gulp a week ago.
I realized that even in a month I will not make the assembly completely satisfying to me.
My task was to find a wp starter that would be intuitive for me. I went through a lot of starters: wpemerge, sage, themosis. But with them I am losing pure wordpress.
I am trying to develop sites in vanilla js, bootstrap grid, flex. Also I want to switch from ACF pro to the free Carbon fields tool or CMB2.
5 minutes ago I received the news that ACF bought Delicious Brains and for some reason everyone is happy about that.))
It may be early to give up ACF))


I am very grateful to you for this build. I hope I can use it and understand everything). If I do not understand something, I will write to you)
I recommend filming a launch video on Brick.

**Comment by stefanobartoletti** [comment]
Thank you, if you are looking for a theme that uses Vanilla JS and Bootstrap and respects WordPress standards instead of fighting them, Bricks could be a nice option, since it does all of this natively.

About Gulp, all of its tasks within Bricks are already pre-configured, you can simply run them without worrying about the underlying configuration.

I don't know about Carbon Fields, but a the moment I'm not planning to switch away from ACF, which is the *de facto* standard for this kinf of tool.

For everything else, please consider reading the documentation hosted on https://bricks.stefanobartoletti.it, it describes all of the theme features and configurations
